import React from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import {
  Image, MessageSquare, Share2, Instagram, Twitter, Facebook
}
  from "lucide-react";
import "../styles/homepage.css";

export default function Home() {
  const { user, logout } = useAuth();
  const handleLogout = () => {
    logout();
  };

  return (
    <div className="home-container">
      {/* Header */}
      <header className="header">
        <div className="header-content">
          <a href="/" className="">
            <div className="logo-section">
              <a href="/" className="">
                <img src="../assets/logo1.png" alt="CapKraft Logo" className="logo-image" />
                {/* <h1 className="logo-title">CapKraft</h1> */}</a>
            </div>

          </a>
          <div className="auth-buttons">
            {user ? (
              <div className="user-info">
                <span className="user-name">Hi, {user.displayName || user.email}</span>
                <button onClick={handleLogout} className="btn-outline">
                  Log out
                </button>
              </div>
            ) : (
              <div className="login-buttons">
                <Link to="/login" className="btn-ghost">Log in</Link>
                <Link to="/signup" className="btn-primary">Sign up</Link>
              </div>
            )}
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="hero-section">
        <div className="hero-content">
          <h1 className="hero-title">Generate Stunning Social Media Posts with AI</h1>
          <p className="hero-subtitle">Create captivating social media content with just a few clicks. Our AI helps you generate eye-catching posts and engaging captions for any platform.</p>

          {user ? (
            <Link to="/Aipost" className="btn-primary-large">
              Create New Post
            </Link>
          ) : (
            <Link to="/signup" className="btn-primary-large">
              Get Started Now
            </Link>
          )}
        </div>
      </section>

      {/* Showcase Section */}
      <section className="showcase-section">
        <h2 className="section-title">See What You Can Create</h2>
        <p className="section-subtitle">Check out some stunning sample posts generated by our AI.</p>

        <div className="showcase-container">
          <div className="showcase-scroll">
            {/* Cards (Image Samples) */}
            <div className="showcase-card">
              <img src="../assets/sample1.png" alt="Sample Post 1" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample2.png" alt="Sample Post 2" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample3.png" alt="Sample Post 3" className="showcase-image" />
            </div>
            {/* <div className="showcase-card">
              <img src="../assets/sample4.png" alt="Sample Post 4" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample5.png" alt="Sample Post 5" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample6.png" alt="Sample Post 6" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample7.png" alt="Sample Post 7" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample8.png" alt="Sample Post 8" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample9.png" alt="Sample Post 9" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample10.png" alt="Sample Post 10" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample11.png" alt="Sample Post 11" className="showcase-image" />
            </div>
            <div className="showcase-card">
              <img src="../assets/sample12.png" alt="Sample Post 12" className="showcase-image" />
            </div> */}
          </div>
        </div>
      </section>


      {/* Features Section */}
      <section className="features-section">
        <h2 className="section-title">How It Works</h2>

        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">
              <Image />
            </div>
            <h3 className="feature-title">1. Choose Platform</h3>
            <p className="feature-text">Choose your platform, select tone, image style and write keywords to get your post ready.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <MessageSquare />
            </div>
            <h3 className="feature-title">2. Generate Captions</h3>
            <p className="feature-text">Our AI analyzes your input and creates engaging, platform-specific captions.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <Share2 />
            </div>
            <h3 className="feature-title">3. Share & Publish</h3>
            <p className="feature-text">Customize your post and share directly to your favorite social platforms.</p>
          </div>
        </div>
      </section>



      {/* Platforms Section */}
      <section className="platforms-section">
        <h2 className="section-title">Generate for Any Platform</h2>
        <p className="section-subtitle">Our AI is trained to create optimized content for all popular social media platforms.</p>

        <div className="platforms-grid">
          <div className="platform-card">
            <Instagram className="platform-icon text-orange-500" />
            <span>Instagram</span>
          </div>
          <div className="platform-card">
            <Facebook className="platform-icon" color="rgb(1, 12, 26)" />
            <span>Facebook</span>
          </div>
          <div className="platform-card">
            <Twitter className="platform-icon" />
            <span>Twitter</span>
          </div>

        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <div className="cta-content">
          <h2 className="cta-title">Ready to Transform Your Social Media?</h2>
          <p className="cta-subtitle">Join Capkraft AI, save time and boost engagement with our AI powered caption generator.</p>

          {user ? (
            <Link to="/Aipost" className="btn-white">
              Get Started
            </Link>
          ) : (
            <Link to="/signup" className="btn-white">
              Create Free Account
            </Link>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-content">
          <div className="logo-section">
            <img src="../assets/logo1.png" alt="CapKraft Logo" className="logo-image" />
          </div>
          <div className="footer-text">
            &copy; {new Date().getFullYear()} CapKraft.
          </div>
        </div>
      </footer>
    </div>
  );
}
